--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/wallpapers/wp1.jpg"

-- Special
background="#0D1214"
foreground="#eeddcb"
cursor="#eeddcb"

-- Colors
color0="#0D1214"
color1="#2A7A81"
color2="#6D7587"
color3="#748E8D"
color4="#9F9A9A"
color5="#D0B198"
color6="#D0BAAA"
color7="#eeddcb"
color8="#a69a8e"
color9="#2A7A81"
color10="#6D7587"
color11="#748E8D"
color12="#9F9A9A"
color13="#D0B198"
color14="#D0BAAA"
color15="#eeddcb"
